Modified notice of assigned hotkeys

diff --git a/gif-anim-cap-frame b/gif-anim-cap-frame
--- a/gif-anim-cap-frame
+++ b/gif-anim-cap-frame
@@ -1,9 +1,9 @@
 #!/bin/bash
-. gif-anim-settings
-if [[ -z "${ga_dir_base+is_def}" ]]; then
-	echo 'Error: gif-anim-settings was not sourced correctly!' >&2
+if ! . gif-anim-settings; then
+	echo 'Error importing gif-anim-settings' >&2
 	exit 1
 fi
+
 # Make dir again since user might have removed frames dir
 # (Like, they selected a position with gif-anim-select-area,
 #  which creates the dir and stores the coordinates, but
diff --git a/gif-anim-make-gif b/gif-anim-make-gif
--- a/gif-anim-make-gif
+++ b/gif-anim-make-gif
@@ -1,10 +1,8 @@
 #!/bin/bash
-. gif-anim-settings
-
-cd "$ga_dir_frames" || {
-	echo "Error! Couldn't access (chdir) to frames cache dir: $ga_dir_frames";
-	exit;
-}
+if ! . gif-anim-settings; then
+	echo 'Error importing gif-anim-settings' >&2
+	exit 1
+fi
 
 echo "Input frames ($ga_dir_frames):"
 ls -gGl *".$ga_frame_ext" | head -5 | sed -e 's/^/ /'
diff --git a/gif-anim-select-area b/gif-anim-select-area
--- a/gif-anim-select-area
+++ b/gif-anim-select-area
@@ -1,18 +1,14 @@
 #!/bin/bash
-. gif-anim-settings
-if [[ -z "$ga_dir_frames" ]]; then
-	echo "FATAL ERROR: \$ga_dir_frames does not seem to be set!" >&2
+if ! . gif-anim-settings; then
+	echo 'Error importing gif-anim-settings' >&2
 	exit 1
 fi
+
 mkdir -p "$ga_dir_base"
 mkdir -p "$ga_dir_frames"
 rm "$ga_dir_frames"/*."$ga_frame_ext"
 
-cat <<'EOT'
-	After border selection, hit:
-	Win-F10 to capture an area
-	Win-F11 to finish
-EOT
+printf '%s' "$ga_hotkey_comments"
 co=$(slop)
 # co=285x184+289+669   # Test
 echo "Coordinates chosen: $co"
