Fixed bug in gif-anim-make-gif where it didn't change to the frames dir.  Updated readme for settings.example.  Removed settings so users can modify their own without it being part of the repo.

diff --git a/gif-anim-make-gif b/gif-anim-make-gif
--- a/gif-anim-make-gif
+++ b/gif-anim-make-gif
@@ -5,6 +5,10 @@ if ! . gif-anim-settings; then
 fi
 
 echo "Input frames ($ga_dir_frames):"
+cd "$ga_dir_frames" || {
+	echo "Error changing to frames dir: $ga_dir_frames" >&2;
+	exit 1;
+}
 ls -gGl *".$ga_frame_ext" | head -5 | sed -e 's/^/ /'
 echo ' ...'
 
